rootUrl = 'https://ladas552.github.io'
language = 'en-us'
title = 'Rattman'
author = 'ladas552'

# Code blocks highlighting
[highlighter]
enable = false
# engine = 'prism' # Can be 'prism' or 'hljs'. Defaults to 'prism'

# RSS feed
[rss]
enable = true
description = 'Latest posts'
ttl = 60
image = '/assets/nix-snowflake-rainbow.svg'

# Content Scheme
## Global options
[content_schema]
required = [ "title", "description", "authors", "categories" ]

## field rules
[content_schema.fields]
title = { type = "string", max_length = 30 }
description = { type = "string", max_length = 100 }
categories = { type = "array", items = { type = "string" }, min_items = 1 }

# publish date for '/posts'
[content_schema.posts.rules]
if = { draft = false }
then = { required = ["publish_date"] }


# Custom additional configuration options with example values
[extra]
license = "GPLv2" # Optional
footer_author_link = "https://github.com/Ladas552" # Optional

# Link_name = "url"
# e.g.
# blog = "/posts"
# GitHub = "https://github.com/NTBBloodbath/norgolith"
[extra.nav]
blog = "/posts"
Github = "https://github.com/Ladas552/ladas552.github.io"
# Link_name = "url"
# GitHub = "https://github.com/NTBBloodbath/norgolith"
[extra.footer]
GitHub = "https://github.com/Ladas552/ladas552.github.io"
