authors = "ladas552"
categories = ["meta"]
created = 2025-02-05T10:11:14
description = "Gratitude to people who helped with the Blog"
title = "Credits"
updated = 2025-02-08T05:48:07
version = "1.1.1"
