authors = ["ladas552"]
categories = ["games"]
created = 2025-02-09T16:31:03+05:00
description = "I played too much Skyrim to say nothing about it"
draft = true
title = "Elder Notes - Skyrim"
updated = 2025-02-09T16:31:26
version = "1.1.1"
