authors = ["ladas552"]
categories = ["cats"]
created = 2025-02-03T10:11:34
description = "Troublesome blob of feline species"
title = "On Owning a Cat"
updated = 2025-02-08T06:06:12
version = "1.1.1"
